### ISSUE TITLE
Error download checkpoints

### ISSUE THREAD

**Issue by R1ckSanchez9x** [VinAIResearch/JointIDSF#3]
Hello VinAIResearch Team,
I tried to download your model checkpoints of JointBERT+CRF and JointIDSF, but i get a error access denied to https://public.vinai.io/ (ERROR 403: Forbidden)

**Comment by joey234** [comment]
Hello there,
I just checked the link and they are working normally. Perhaps you entered a wrong address? Could you try again using these  links:
JointIDSF
http://public.vinai.io/JointIDSF_PhoBERTencoder.tar.gz
http://public.vinai.io/JointIDSF_XLM-Rencoder.tar.gz
JointBERT+CRF
http://public.vinai.io/JointBERT-CRF_PhoBERTencoder.tar.gz
http://public.vinai.io/JointBERT-CRF_XLM-Rencoder.tar.gz

**Comment by R1ckSanchez9x** [comment]
Hi @joey234,
Sorry it's my fall, i entered a wrong link. It's oke now !
Thanks for your response !
