### ISSUE TITLE
Run inference with model checkpoints

### ISSUE THREAD

**Issue by R1ckSanchez9x** [VinAIResearch/JointIDSF#4]
I downloaded your model checkpoints, and ran predict.py with these checkpoints, but I got some errors:
1. It seems that in the file training_args.bin data_path you set "data" instead "PhoATIS"
2. OSERROR: as far as i know this error occurs when i didn't train JointBERT first, but i'm using checkpoints of JointBERT to make inference
![image](https://user-images.githubusercontent.com/61724310/136010807-79bb9307-8577-464b-8deb-00ac032a54fe.png)
![image](https://user-images.githubusercontent.com/61724310/136011498-f60f2bee-eca7-460d-a42c-c8085d1f29ff.png)
![image](https://user-images.githubusercontent.com/61724310/136011770-06a1c0b0-3266-479a-bb23-a5efa3fdd28a.png)

Did i miss any step before run predict.py ?

**Comment by joey234** [comment]
Mind sharing your run command?
I was able to run prediction with a command like this:
```
python3 predict.py --input_file PhoATIS/word-level/test/seq.in \
                   --output_file predictions.txt \
                   --model_dir JointIDSF_PhoBERTencoder
```
I see that you only have the `JointBERT-CRF_PhoBERTencoder` model in your directory so maybe you input the wrong model name into `--model_dir`?

**Comment by joey234** [comment]
Hmm, it's weird.
From your first point above, can you try renaming the name of the folder `PhoATIS` into `data` and run the prediction script again?

**Comment by joey234** [comment]
Thanks for pointing this out.
It's weird that the pretrained checkpoints have the wrong name. I guess i made a mistake in naming the checkpoints.

Could you try putting all files in the `JointBERT-CRF_PhoBERTencoder` inside a path like this `JointBERT_PhoBERTencoder/3e-5/0.6/100`

<img width="377" alt="Screen Shot 2021-10-06 at 02 18 11" src="https://user-images.githubusercontent.com/12378617/136052344-6ed5e265-efb7-436b-a049-8c31cd90ce2e.png">

and then for the `--model_dir` it should be `JointBERT_PhoBERTencoder/3e-5/0.6/100`

**Comment by R1ckSanchez9x** [comment]
I fixed the path of  pretrained checkpoints and it's oke now.
Thanks for your response !!!
