### ISSUE TITLE
Chia sẻ 5 seed chạy trong paper

### ISSUE THREAD

**Issue by Dean98AI** [VinAIResearch/JointIDSF#6]
Mình đang muốn so sánh kết quả chạy của paper với các paper khác, bên bạn có thể share 5 seed các bạn chạy để ra kết quả như trong paper được không ? (các tham số setup chạy đều giữ nguyên trong cả 5 seed đúng không bạn), mình cảm ơn các bạn nhiều

**Comment by joey234** [comment]
Hi bạn, các seed chạy lần lượt là 1, 10, 100, 1000, 1000000 và các hyper-param khác được giữ nguyên.

**Comment by BlackPanther-9x** [comment]
cảm ơn bạn nhiều nhé

**Comment by BlackPanther-9x** [comment]
@joey234 bạn cho mình hỏi là seed chạy cao nhất bên bạn là 100 đúng không bạn, nếu có thể bạn có thể cho mình xin weight các seed chạy model base là joint-bert cho word-level, mình đang thử kết quả một số paper , mình chỉ có mục đích nghiên cứu chứ không sử dụng bất kỳ vào mục đích thương mại nào ( nếu có thể bạn share với mình email này với 20161014@student.hust.edu.vn, mình cảm ơn bạn nhiều)
